apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: livy
  name: livy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: livy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: livy
    spec:
      containers:
        - image: public.ecr.aws/jampp/livy:2.4.0
          name: livy
          ports:
            - containerPort: 8998
          resources: {}
      restartPolicy: Always
status: {}
