apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: metrics
  name: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: metrics
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/: "true"
        io.kompose.service: metrics
    spec:
      containers:
        - image: prom/statsd-exporter
          name: metrics
          ports:
            - containerPort: 9102
          resources: {}
      restartPolicy: Always
status: {}
