apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: minio
    spec:
      containers:
        - args:
            - -c
            - /usr/bin/minio server /data
          command:
            - sh
          env:
            - name: MINIO_ACCESS_KEY
              value: minio_user
            - name: MINIO_SECRET_KEY
              value: minio_key
          image: minio/minio:RELEASE.2020-10-18T21-54-12Z
          name: minio
          ports:
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
status: {}
