apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    io.kompose.service: trino-claim0
  name: trino-claim0
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/Users/rama/Desktop/data-docker-images/trino/conf/"
status: {}
