apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: trino
  name: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: trino
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: trino
    spec:
      containers:
        - env:
            - name: S3_ACCESS_KEY
              value: minio_user
            - name: S3_ENDPOINT
              value: http://minio:9000
            - name: S3_SECRET_KEY
              value: minio_key
          image: trinodb/trino:408
          name: trino
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /etc/trino
              name: trino-claim0
      restartPolicy: Always
      volumes:
        - name: trino-claim0
          persistentVolumeClaim:
            claimName: trino-claim0
status: {}
