apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: airflow
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airflow
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: airflow
    spec:
      containers:
        - env:
            - name: AIRFLOW__SCHEDULER__STATSD_HOST
              value: metrics
            - name: AIRFLOW__SCHEDULER__STATSD_ON
              value: "True"
            - name: AIRFLOW__SCHEDULER__STATSD_PORT
              value: "9125"
            - name: AIRFLOW__SCHEDULER__STATSD_PREFIX
              value: wolfria
            - name: AWS_ACCESS_KEY_ID
              value: minio_user
            - name: AWS_SECRET_ACCESS_KEY
              value: minio_key
            - name: S3_ACCESS_KEY
              value: minio_user
            - name: S3_ENDPOINT
              value: http://minio:9000
            - name: S3_SECRET_KEY
              value: minio_key
          image: public.ecr.aws/jampp/airflow:3.0.0
          name: airflow
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /home/airflow/conf/
              name: airflow-claim0
      restartPolicy: Always
      volumes:
        - name: airflow-claim0
          persistentVolumeClaim:
            claimName: airflow-claim0
status: {}
