apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: download-s3-data
  name: download-s3-data
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: download-s3-data
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: download-s3-data
    spec:
      containers:
        - command:
            - /download_s3_data.sh
          env:
            - name: MINIO_ACCESS_KEY
            - name: MINIO_HOST
            - name: MINIO_SECRET_KEY
            - name: S3_ACCESS_KEY
            - name: S3_HOST
            - name: S3_SECRET_KEY
          image: minio/mc:latest
          name: download-s3-data
          resources: {}
          volumeMounts:
            - mountPath: /download_s3_data.sh
              name: download-s3-data-claim0
            - mountPath: /file_paths.txt
              name: download-s3-data-claim1
      restartPolicy: Always
      volumes:
        - name: download-s3-data-claim0
          persistentVolumeClaim:
            claimName: download-s3-data-claim0
        - name: download-s3-data-claim1
          persistentVolumeClaim:
            claimName: download-s3-data-claim1
status: {}
